val fallbackPosters = mapOf(
    "légion" to "https://upload.wikimedia.org/wikipedia/en/7/77/Legion_Poster.jpg",
    "le secret des marrowbone" to "https://upload.wikimedia.org/wikipedia/en/9/91/Marrowbone_%28film%29.png",
    "le prestige" to "https://upload.wikimedia.org/wikipedia/en/8/8a/The_Prestige_poster.jpg",
    "le nouveau testament" to "https://upload.wikimedia.org/wikipedia/en/2/23/The_Brand_New_Testament.jpg",
    "inception" to "https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg",
    "a la croisée des mondes" to "https://static.tvmaze.com/uploads/images/original_untouched/445/1113926.jpg",
    "a knight of the seven kingdoms" to "https://static.tvmaze.com/uploads/images/original_untouched/608/1521912.jpg",
    "american gods" to "https://static.tvmaze.com/uploads/images/original_untouched/289/722622.jpg",
    "barry" to "https://static.tvmaze.com/uploads/images/original_untouched/455/1138151.jpg",
    "black list" to "https://static.tvmaze.com/uploads/images/original_untouched/208/522372.jpg",
    "common side effects" to "https://static.tvmaze.com/uploads/images/original_untouched/553/1384654.jpg",
    "halo" to "https://static.tvmaze.com/uploads/images/original_untouched/502/1256105.jpg",
    "his dark materials" to "https://static.tvmaze.com/uploads/images/original_untouched/445/1113926.jpg",
    "la palma" to "https://static.tvmaze.com/uploads/images/original_untouched/545/1364327.jpg",
    "le prophète" to "https://static.tvmaze.com/uploads/images/original_untouched/224/562050.jpg",
    "lost" to "https://static.tvmaze.com/uploads/images/original_untouched/0/1389.jpg",
    "monarch" to "https://static.tvmaze.com/uploads/images/original_untouched/423/1059888.jpg",
    "pamela rose" to "https://static.tvmaze.com/uploads/images/original_untouched/487/1219908.jpg",
    "plaine orientale" to "https://static.tvmaze.com/uploads/images/original_untouched/567/1418683.jpg",
    "the great" to "https://static.tvmaze.com/uploads/images/original_untouched/460/1151199.jpg",
    "the librarians" to "https://static.tvmaze.com/uploads/images/original_untouched/135/338167.jpg",
    "the witcher" to "https://static.tvmaze.com/uploads/images/original_untouched/594/1486674.jpg",
    "tom clancy's jack ryan" to "https://static.tvmaze.com/uploads/images/original_untouched/486/1215704.jpg",
    "tulsa king" to "https://static.tvmaze.com/uploads/images/original_untouched/588/1471782.jpg",
    "west world" to "https://static.tvmaze.com/uploads/images/original_untouched/385/964908.jpg",
    "démon slave" to "https://upload.wikimedia.org/wikipedia/en/9/90/Chained_Soldier_manga_volume_1_cover.jpg",
    "full métal alchimiste" to "https://upload.wikimedia.org/wikipedia/en/9/9d/Fullmetal_Alchemist_Brotherhood_key_visual.png",
    "nukitashi" to "https://static.tvmaze.com/uploads/images/original_untouched/608/1521382.jpg"
)
